### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by eparizzi** [daquinoaldo/https-localhost#5]
`npm i -g https-localhost`

> Cannot generate the localhost certificate on your platform. Please, consider contacting the developer if you can help.

Windows 10 Pro x64

**Comment by daquinoaldo** [comment]
Hi Emiliano!

Thank you for your contribution!

I found the bug and I'm working on it. Just the time to improve tests and I'll push the fix. I'll keep you updated!

**Comment by daquinoaldo** [comment]
Waiting the [travis build](https://travis-ci.com/daquinoaldo/https-localhost/builds/102411645) to finish.

**Comment by eparizzi** [comment]
Let me know if you need me to test it on Windows.

**Comment by daquinoaldo** [comment]
I cannot perform tests on Travis, due to missing permissions and functionalities. I've done some tests on a VM and it seems work to me.

@eparizzi can you test it, please?
```
npm install -g git+https://git@github.com/daquinoaldo/https-localhost.git
```

**Comment by daquinoaldo** [comment]
> Let me know if you need me to test it on Windows.

Ping @eparizzi

**Comment by daquinoaldo** [comment]
I have tested it on a native Windows 10 Home machine and seems work.
I've published the patch on NPM, so I close this issue. Please, re-open if still be bugged.
Thank you again for reporting the bug!

**Comment by r3wt** [comment]
This still doesn't work on windows, even when running command prompt as admin.

`ERROR: failed to execute "keytool -importcert": exit status 1` tried it first in mingw, then tried again in adminstrative command prompt. it says access denied

**Comment by daquinoaldo** [comment]
Hi @r3wt,
I've tested right now on Windows but I'm not able to reproduce this error.
Anyway, I have good reasons to think that is a different problem to the one for which this issue was opened.
Could you please open a new issue providing some steps to reproduce? You can reset the original condition by removing the folder https-localhost from `%APPDATA%`.
Thank you for your cooperation!

Aldo

**Comment by r3wt** [comment]
@daquinoaldo in my case it was caused by JAVA_HOME being set

**Comment by daquinoaldo** [comment]
@r3wt may be a problem related to [mkcert](https://github.com/FiloSottile/mkcert). Anyway, I'm happy you have fixed it.

**Comment by r3wt** [comment]
@daquinoaldo thanks man, i really appreciate this project, very useful for local development when needing https. +1
